version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  test:
    build: .
    volumes:
      - .:/usr/src/app
    command: npm test

  lint:
    build: .
    volumes:
      - .:/usr/src/app
    command: npm run lint